version: '3'
services:
  app:
    build: .
    container_name: shop-api-app
    restart: always
    environment:
      - APP_ENV=development
      - PORT=8080
    ports:
      - "8082:8080"
    command: npm run start.dev
    working_dir: /app
